name: Publish canary

on:
  push:
    branches:
      - develop
      - release

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      version-suffix: "alpha.${{ github.run_number }}"

  publish-nuget:
    uses: ./.github/workflows/publish-nuget-packages.yml
    if: github.repository_owner == 'dequelabs' # don't attempt to publish from forks
    needs: ["build-and-test"]
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
