name: Publish NuGet packages

on:
  # This is a reusable workflow, not intended to be invoked directly
  workflow_call:
    inputs:
      packages-artifact-name:
        description: "Name of a previously-uploaded artifact containing a flat collection of .nupkg files to publish"
        default: packages # matches what ./build-and-test.yml produces
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Download packages artifact from build-and-test job
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.packages-artifact-name }}
          path: ${{ github.workspace }}/packages

      - name: List packages to be published
        run: ls packages

      # Order is important - if publishing Commons fails, we want the job to abort without attempting the others
      #
      # TODO: drop the "echo [DRY RUN]" wrapper once the NuGet publishing account is established in #38
      - name: Publish Deque.AxeCore.Commons to NuGet
        run: dotnet nuget push packages/Deque.AxeCore.Commons.*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json

      - name: Publish Deque.AxeCore.Selenium to NuGet
        run: dotnet nuget push packages/Deque.AxeCore.Selenium.*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
      
      - name: Publish Deque.AxeCore.Playwright to NuGet
        run: dotnet nuget push packages/Deque.AxeCore.Playwright.*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
